// ============================================
// land.on/pad - Mock San Francisco Listings
// ============================================

import type { Listing, MovingTask, Application, SettleItem } from '../types';

export const mockListings: Listing[] = [
  {
    id: '1',
    price: 2450,
    address: '742 Valencia Street',
    neighborhood: 'Mission District',
    floor: '2nd Floor',
    beds: 1,
    baths: 1,
    sqft: 680,
    imageUrl: 'https://images.unsplash.com/photo-1663756915301-2ba688e078cf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBhcGFydG1lbnQlMjBsaXZpbmclMjByb29tfGVufDF8fHx8MTc3MTE2MjA2OXww&ixlib=rb-4.1.0&q=80&w=1080',
    aiMatch: 'perfect',
    aiInsight: 'Walking distance to BART and tons of restaurants. The south-facing windows get excellent natural light all day.',
    saved: false,
    petFriendly: true,
    hasLaundry: false,
    nearTransit: true,
    availableDate: 'Mar 1, 2026',
    badge: { text: 'Perfect Match', color: 'teal' },
  },
  {
    id: '2',
    price: 3100,
    address: '1847 Church Street',
    neighborhood: 'Noe Valley',
    floor: '1st Floor',
    beds: 2,
    baths: 1,
    sqft: 950,
    imageUrl: 'https://images.unsplash.com/photo-1611095459865-47682ae3c41c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb3p5JTIwYmVkcm9vbSUyMGludGVyaW9yfGVufDF8fHx8MTc3MTIzMzYxNnww&ixlib=rb-4.1.0&q=80&w=1080',
    aiMatch: 'perfect',
    aiInsight: 'Quiet family-friendly street with a backyard garden. Ground floor means easy move-in and pet access.',
    saved: false,
    petFriendly: true,
    hasLaundry: true,
    nearTransit: true,
    availableDate: 'Mar 15, 2026',
    badge: { text: 'Perfect Match', color: 'teal' },
  },
  {
    id: '3',
    price: 2800,
    address: '455 Castro Street',
    neighborhood: 'Castro',
    floor: '3rd Floor',
    beds: 1,
    baths: 1,
    sqft: 750,
    imageUrl: 'https://images.unsplash.com/photo-1696986681606-b156ccd761c5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsdXh1cnklMjBraXRjaGVufGVufDF8fHx8MTc3MTI1NzQwM3ww&ixlib=rb-4.1.0&q=80&w=1080',
    aiMatch: 'maybe',
    aiInsight: 'Great neighborhood vibe and walkability. Slightly above budget but includes in-unit washer/dryer which saves ~$80/mo.',
    saved: false,
    petFriendly: false,
    hasLaundry: true,
    nearTransit: true,
    availableDate: 'Feb 28, 2026',
    badge: { text: 'Worth a Look', color: 'amber' },
  },
  {
    id: '4',
    price: 3500,
    address: '88 Townsend Street #4F',
    neighborhood: 'SOMA',
    floor: '4th Floor',
    beds: 2,
    baths: 2,
    sqft: 1100,
    imageUrl: 'https://images.unsplash.com/photo-1768118422932-4cdcca2ced8f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhcGFydG1lbnQlMjBiYWxjb255JTIwdmlld3xlbnwxfHx8fDE3NzEyNTU1NDR8MA&ixlib=rb-4.1.0&q=80&w=1080',
    aiMatch: 'maybe',
    aiInsight: 'Modern building with gym and rooftop. Close to Caltrain for South Bay commute. Extra bedroom works as office.',
    saved: false,
    petFriendly: false,
    hasLaundry: true,
    nearTransit: true,
    availableDate: 'Apr 1, 2026',
    badge: { text: 'Worth a Look', color: 'amber' },
  },
  {
    id: '5',
    price: 2200,
    address: '1221 Haight Street',
    neighborhood: 'Haight-Ashbury',
    floor: '2nd Floor',
    beds: 1,
    baths: 1,
    sqft: 600,
    imageUrl: 'https://images.unsplash.com/photo-1595515106886-43b1443a2e8b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb250ZW1wb3JhcnklMjBiYXRocm9vbXxlbnwxfHx8fDE3NzExODIyNjd8MA&ixlib=rb-4.1.0&q=80&w=1080',
    aiMatch: 'perfect',
    aiInsight: 'Best value in SF right now. Charming Victorian with original details. Golden Gate Park is 2 blocks away.',
    saved: false,
    petFriendly: true,
    hasLaundry: false,
    nearTransit: false,
    availableDate: 'Mar 1, 2026',
    badge: { text: 'Best Value', color: 'teal' },
  },
  {
    id: '6',
    price: 2650,
    address: '380 Guerrero Street',
    neighborhood: 'Mission District',
    floor: 'Ground Floor',
    beds: 1,
    baths: 1,
    sqft: 720,
    imageUrl: 'https://images.unsplash.com/photo-1740416249095-2380ee85a75d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx1cmJhbiUyMGxvZnQlMjBzcGFjZXxlbnwxfHx8fDE3NzEyNTc0MDR8MA&ixlib=rb-4.1.0&q=80&w=1080',
    aiMatch: 'perfect',
    aiInsight: 'Ground floor with private entrance — great for your dog. Dolores Park is a 5-minute walk.',
    saved: false,
    petFriendly: true,
    hasLaundry: false,
    nearTransit: true,
    availableDate: 'Feb 20, 2026',
    badge: { text: 'Just Listed', color: 'teal' },
  },
  {
    id: '7',
    price: 3200,
    address: '2250 Market Street #3B',
    neighborhood: 'Castro',
    floor: '3rd Floor',
    beds: 2,
    baths: 1.5,
    sqft: 900,
    imageUrl: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb2Rlcm4lMjBhcGFydG1lbnR8ZW58MXx8fHwxNzY5MDAwMDAwfDA&ixlib=rb-4.1.0&q=80&w=1080',
    aiMatch: 'maybe',
    aiInsight: 'Renovated unit with updated kitchen. No pets allowed which is a dealbreaker for your situation.',
    saved: false,
    petFriendly: false,
    hasLaundry: true,
    nearTransit: true,
    availableDate: 'Mar 10, 2026',
    badge: { text: 'Renovated', color: 'amber' },
  },
  {
    id: '8',
    price: 2900,
    address: '567 Hayes Street',
    neighborhood: 'Hayes Valley',
    floor: '2nd Floor',
    beds: 1,
    baths: 1,
    sqft: 800,
    imageUrl: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhcGFydG1lbnQlMjBpbnRlcmlvcnxlbnwxfHx8fDE3NjkwMDAwMDB8MA&ixlib=rb-4.1.0&q=80&w=1080',
    aiMatch: 'perfect',
    aiInsight: 'Walkable to everything — restaurants, shops, transit. Building allows cats and small dogs.',
    saved: false,
    petFriendly: true,
    hasLaundry: false,
    nearTransit: true,
    availableDate: 'Mar 5, 2026',
    badge: { text: 'Perfect Match', color: 'teal' },
  },
  {
    id: '9',
    price: 3400,
    address: '101 Brannan Street #8A',
    neighborhood: 'SOMA',
    floor: '8th Floor',
    beds: 2,
    baths: 2,
    sqft: 1050,
    imageUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhcGFydG1lbnQlMjBsaXZpbmclMjByb29tfGVufDF8fHx8MTc2OTAwMDAwMHww&ixlib=rb-4.1.0&q=80&w=1080',
    aiMatch: 'dealbreaker',
    aiInsight: 'Stunning views but no pets allowed and 45-min commute to your office. Building has strict quiet hours after 9pm.',
    saved: false,
    petFriendly: false,
    hasLaundry: true,
    nearTransit: false,
    availableDate: 'Apr 15, 2026',
    badge: { text: 'Check Dealbreakers', color: 'coral' },
  },
  {
    id: '10',
    price: 2350,
    address: '1450 Noriega Street',
    neighborhood: 'Sunset District',
    floor: '1st Floor',
    beds: 2,
    baths: 1,
    sqft: 850,
    imageUrl: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhcGFydG1lbnQlMjBiZWRyb29tfGVufDF8fHx8MTc2OTAwMDAwMHww&ixlib=rb-4.1.0&q=80&w=1080',
    aiMatch: 'maybe',
    aiInsight: 'Great price for a 2-bedroom but far from downtown. Quiet area with ocean breeze. Bus to BART takes 25 min.',
    saved: false,
    petFriendly: true,
    hasLaundry: false,
    nearTransit: false,
    availableDate: 'Mar 1, 2026',
    badge: { text: 'Price Drop', color: 'amber' },
  },
  {
    id: '11',
    price: 2750,
    address: '3322 24th Street',
    neighborhood: 'Mission District',
    floor: '2nd Floor',
    beds: 1,
    baths: 1,
    sqft: 650,
    imageUrl: 'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhcGFydG1lbnQlMjBraXRjaGVufGVufDF8fHx8MTc2OTAwMDAwMHww&ixlib=rb-4.1.0&q=80&w=1080',
    aiMatch: 'perfect',
    aiInsight: 'Steps from 24th Street BART. Murals, taquerias, and a vibrant neighborhood. Pet-friendly with shared yard.',
    saved: false,
    petFriendly: true,
    hasLaundry: false,
    nearTransit: true,
    availableDate: 'Feb 25, 2026',
    badge: { text: 'Hot Property', color: 'teal' },
  },
  {
    id: '12',
    price: 3150,
    address: '890 Potrero Avenue #2C',
    neighborhood: 'Potrero Hill',
    floor: '2nd Floor',
    beds: 2,
    baths: 1,
    sqft: 1000,
    imageUrl: 'https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhcGFydG1lbnQlMjB2aWV3fGVufDF8fHx8MTc2OTAwMDAwMHww&ixlib=rb-4.1.0&q=80&w=1080',
    aiMatch: 'maybe',
    aiInsight: 'Amazing city views from Potrero Hill. Sunny microclimate. Close to Whole Foods and Anchor Brewing.',
    saved: false,
    petFriendly: false,
    hasLaundry: true,
    nearTransit: true,
    availableDate: 'Mar 20, 2026',
    badge: { text: 'Great Views', color: 'amber' },
  },
];

export const mockTasks: MovingTask[] = [
  {
    id: '1',
    title: 'Submit rental application',
    dueDate: 'Feb 18, 2026',
    status: 'overdue',
    category: 'Application',
    description: 'Complete application for 742 Valencia Street',
    energyLevel: 'high',
  },
  {
    id: '2',
    title: 'Schedule move-in inspection',
    dueDate: 'Feb 22, 2026',
    status: 'due-soon',
    category: 'Inspection',
    description: 'Walk-through with landlord to document condition',
    energyLevel: 'medium',
  },
  {
    id: '3',
    title: 'Book moving company',
    dueDate: 'Feb 25, 2026',
    status: 'on-track',
    category: 'Moving',
    description: 'Get quotes from 3+ SF movers',
    energyLevel: 'medium',
  },
  {
    id: '4',
    title: 'Transfer PG&E and internet',
    dueDate: 'Feb 28, 2026',
    status: 'on-track',
    category: 'Utilities',
    description: 'Set up electric, gas, Xfinity/Sonic internet',
    energyLevel: 'low',
  },
  {
    id: '5',
    title: 'Update mailing address',
    dueDate: 'Mar 1, 2026',
    status: 'on-track',
    category: 'Admin',
    description: 'USPS, bank, employer, subscriptions',
    energyLevel: 'low',
  },
  {
    id: '6',
    title: 'Pack kitchen items',
    dueDate: 'Feb 15, 2026',
    status: 'completed',
    category: 'Packing',
    energyLevel: 'high',
  },
  {
    id: '7',
    title: 'Pack bedroom items',
    dueDate: 'Feb 16, 2026',
    status: 'completed',
    category: 'Packing',
    energyLevel: 'medium',
  },
  {
    id: '8',
    title: 'Notify current landlord',
    dueDate: 'Feb 20, 2026',
    status: 'due-soon',
    category: 'Admin',
    description: 'Give 30-day written notice',
    energyLevel: 'low',
  },
  {
    id: '9',
    title: 'Cancel current renters insurance',
    dueDate: 'Mar 5, 2026',
    status: 'on-track',
    category: 'Insurance',
    description: 'Switch to new address with Lemonade',
    energyLevel: 'low',
  },
];

export const mockApplications: Application[] = [
  {
    id: '1',
    address: '742 Valencia Street',
    status: 'in-progress',
    documents: [
      { id: 'd1', name: 'Photo ID', type: 'id', uploaded: true, required: true },
      { id: 'd2', name: 'Pay Stubs (last 3 months)', type: 'income', uploaded: true, required: true },
      { id: 'd3', name: 'Bank Statement', type: 'income', uploaded: false, required: true },
      { id: 'd4', name: 'Previous Landlord Reference', type: 'reference', uploaded: false, required: true },
      { id: 'd5', name: 'Employment Letter', type: 'income', uploaded: true, required: false },
    ],
    notes: 'Landlord responds within 48 hours. Application fee: $45.',
  },
];

export const mockSettleItems: SettleItem[] = [
  {
    id: 's1',
    title: 'Set up PG&E account',
    description: 'Transfer gas and electric to your name',
    category: 'utilities',
    completed: false,
    icon: '⚡',
  },
  {
    id: 's2',
    title: 'Set up internet',
    description: 'Schedule Xfinity or Sonic installation',
    category: 'utilities',
    completed: false,
    icon: '📡',
  },
  {
    id: 's3',
    title: 'Get renters insurance',
    description: 'Required by most SF landlords',
    category: 'utilities',
    completed: false,
    icon: '🛡️',
  },
  {
    id: 's4',
    title: 'Update DMV address',
    description: 'California requires update within 10 days',
    category: 'address-change',
    completed: false,
    icon: '🚗',
  },
  {
    id: 's5',
    title: 'Update bank address',
    description: 'All financial accounts',
    category: 'address-change',
    completed: false,
    icon: '🏦',
  },
  {
    id: 's6',
    title: 'Set up mail forwarding',
    description: 'USPS forward for 6 months',
    category: 'address-change',
    completed: false,
    icon: '📬',
  },
  {
    id: 's7',
    title: 'Find nearest grocery store',
    description: 'Check out local markets and Trader Joe\'s',
    category: 'neighborhood',
    completed: false,
    icon: '🛒',
  },
  {
    id: 's8',
    title: 'Locate nearest laundromat',
    description: 'If no in-unit laundry, find closest option',
    category: 'neighborhood',
    completed: false,
    icon: '👕',
  },
  {
    id: 's9',
    title: 'Find your coffee shop',
    description: 'Every SF neighborhood has a gem',
    category: 'neighborhood',
    completed: false,
    icon: '☕',
  },
  {
    id: 's10',
    title: 'Unpack essentials box',
    description: 'Toiletries, bedding, phone charger, coffee maker',
    category: 'setup',
    completed: false,
    icon: '📦',
  },
  {
    id: 's11',
    title: 'Test all locks and windows',
    description: 'Document any issues with landlord',
    category: 'setup',
    completed: false,
    icon: '🔑',
  },
  {
    id: 's12',
    title: 'Meet a neighbor',
    description: 'Building community starts with hello',
    category: 'neighborhood',
    completed: false,
    icon: '👋',
  },
];

export const filterOptions: string[] = [
  'All Listings',
  'Perfect Matches',
  'Worth a Look',
  'Saved',
  'Under $3000',
  'Pet Friendly',
  'In-Unit Laundry',
  'Near Transit',
];

export const suggestionChips: string[] = [
  'Ground floor or higher',
  'Pet-friendly',
  'Near BART',
  'Natural light',
  'In-unit laundry',
  'Under $2800',
  'Quiet neighborhood',
];
